Reason for dependency
=====================

Several modules have been changed which the r38691 version opf the FBX scripts rely on.
The errors at the end of this document occur with the original v2.58a script modules.

Simply replace the release scripts with the r38691 scripts.


25 July 2011
===


found bundled python: C:\Program Files\Blender Foundation\Blender\2.58\python
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.58\scripts\modules\addon_utils.py", line 207, in enable    mod = __import__(module_name)
  File "C:\Program Files\Blender Foundation\Blender\2.58\scripts\addons\io_scene_fbx\__init__.py", line 45, in <module>    from bpy_extras.io_utils import (ExportHelper,ImportError: cannot import name axis_conversion_ensure



===


found bundled python: C:\Program Files\Blender Foundation\Blender\2.58\python
read blend: U:\My Documents\SavedGames\PrepModels\TestDudeAnimations2.blend

FBX export starting... 'U:\\My Documents\\SavedGames\\PrepModels\\TestDudeAnimat
ions2-orig.fbx'
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.58\scripts\addons\io_scene
_fbx\__init__.py", line 156, in execute
    return export_fbx.save(self, context, **keywords)
  File "C:\Program Files\Blender Foundation\Blender\2.58\scripts\addons\io_scene
_fbx\export_fbx.py", line 2796, in save
    return save_single(operator, context.scene, filepath, **kwargs_mod)
  File "C:\Program Files\Blender Foundation\Blender\2.58\scripts\addons\io_scene
_fbx\export_fbx.py", line 2195, in save_single
    write_video(texname, tex)
  File "C:\Program Files\Blender Foundation\Blender\2.58\scripts\addons\io_scene
_fbx\export_fbx.py", line 1130, in write_video
    fname_strip = bpy.path.basename(fname_rel)
AttributeError: 'module' object has no attribute 'basename'

location:<unknown location>:-1

location:<unknown location>:-1

